### ISSUE TITLE
Google Login Button

### ISSUE THREAD

**Issue by jameszu** [UoaWDCC/AEYB#1]
### Outcome
As a board member, I can login or sign up for the webapp

### Moment
Login page with "Login using Google" button

### Key Results

- [x] Implement the button itself
- [x] Code the desired design from the [designer's wireframe](https://aeyb.invisionapp.com/freehand/AEYB-Wireframes-WIhWTZOfE)
- [x] Implement the authenticate with google
- [x] Code checked by another developer
- [x] Create pull request

**Comment by pumbas600** [comment]
Hey guys, so to integrate the login system to the backend, here's what you'll need to do:
> Note: I've not yet got the google client id, but I'll do that soon and let y'all know.

To run the backend server, go to the backend folder and run `npm run dev`.

1. Using [`react-google-login`](https://www.npmjs.com/package/react-google-login), add the following to your code:
```ts
function onSuccess(response) {
    console.log(response);
}

function onFailure(response) {
    console.log(response);
}

//...

<GoogleLogin
    clientId="Google client ID that I have not yet got"
    buttonText="Login"
    onSuccess={onSuccess}
    onFailure={onFailure}
    cookiePolicy={'single_host_origin'}
/>
```
2. In the `onSuccess` callback, you'll want to send a `POST` request to the `/api/users/login` endpoint with the `response.tokenId` as the credential:
```json
{
    "credential": "The ID token"
}
```
> Note: This response should also contain information about the current user such as email, name and profile picture.

3. In response to the `POST` request, you should receive something along the lines of:
```json
{
    "status": "success",
    "token": "The token used to authorize future requests!",
    "data": {
        "id": "1234",
        "name": "Josh Testing",
        "permissions": [
            "VIEW_ROLES",
            "ADD_ROLES",
            "VIEW_USERS",
            "UPDATE_USERS"
        ]
    }
}
````
4. You should save the token to the `localStorage` and use that to check if you need to log in.

5. If you're using `axios`, you can configure a specific instance to use the token received automatically like so:
```js
const api = axios.create({
    baseUrl: 'http://localhost:5000',  // TODO: Change this depending on if its in development
    headers: {
        Authorization : `Bearer ${localStorage.getItem("access_token")`
    }
});
```
Any future requests using `api` will automatically use the access token.

**Comment by pumbas600** [comment]
Oh, As I've not been able to test the google login part yet, there will likely be some issues so let me know once you get up to the `POST` request to the backend as there will likely be some bugs that need to be smoothed out :)
