### ISSUE TITLE
Implementing new DB schemas

### ISSUE THREAD

**Issue by jacobatan** [UoaWDCC/AEYB#123]
### Outcome

Once #115 is complete, we shall implement the new DB schemas

### Key Results

- [x] Implement the new DB Schemas
- [x] Run a data migration ( maybe(?) if we are in PROD, if not just drop the entire collection)
- [ ] Back test EVERYTHING
- [ ] Make sure all existing endpoints work
- [ ] Make sure all frontend components can do their respective CRUD functionalities.

And a couple others that we can keep adding...

**Comment by chrisv09** [comment]
We will drop the whole database in time
