### ISSUE TITLE
Role endpoint additional features

### ISSUE THREAD

**Issue by pumbas600** [UoaWDCC/AEYB#14]
### Outcome

In #7 and #2, the minimum viable product for roles and permissions was created, allowing for users to create, update, delete and get roles and their associated permissions, along with assigning those roles to users. 

However, there exists the potential to improve the usability of this API.

### Moment

The minimum viable product has already been created as per #7 and #2. These additional features will help with the usability of the API.

### Key Results

- [x] Include a counter of the number of users with each role in the GET roles request?
- [x] Delete role endpoint to remove the role from any users who currently have it
- [x] Add role to user endpoint
- [x] Remove role from user endpoint

**Queries:**
Currently when assigning permissions to roles (And similarly for assigning roles to users), if you want to add a role to the user you need to send a `PATCH` request with the updated permissions, including all the current permissions and the new permission. Do you think this is fine, or should we include separate endpoints for adding roles and removing roles?

**Comment by lpar105** [comment]
I think a separate endpoint for adding/removing a role to/from a user is worthwhile!

I'll include it in the work on this issue :)
