### ISSUE TITLE
Error message to let the user know they can't perform a certain action

### ISSUE THREAD

**Issue by unix2dossss** [UoaWDCC/AEYB#151]
### Outcome

 The user should be informed clearly and succinctly that they cannot perform a certain action to avoid confusion or frustration.

### Key Results

- [ ] **Discuss with Jacob/Tyler what sort of error message we want.**
    - I was thinking: a little pop up rectangle at the top of the page, which says 'X action cannot be performed.' with a little X on the right hand-side for the user to close the message.

Something possibly like this:
![image](https://github.com/UoaWDCC/aeyb-monitor/assets/60042992/480ed6fb-0b79-418d-ab92-0f1fccbd6e44)
 
- [ ] **Create component.**

**Comment by jacobatan** [comment]
Yes, something like that would be perfect. We could also have more general error messages such as, "Oops, something went wrong..." for any of our API errors that aren't meaningful. But I am SUPER happy with what you have :)
