### ISSUE TITLE
Permission Handling 

### ISSUE THREAD

**Issue by lpar105** [UoaWDCC/AEYB#23]
### Outcome

The AEYB webapp includes permission handling that considers a uses roles and each roles permission reach

### Moment

Middleware's that check:
- Permission and reach: If you can do something, within a specific group
- Interaction: Additional middleware for when multiple users are involved, eg: can user A see/edit user B's data.
- Balance: Additional middleware for when roles are involved, prevents you from doing anything that gives you more, or takes away from your own permissions/reach

### Key Results

-----------------------------------
**BASIC SETUP**
- [x] Create group endpoint
- [x] Delete group endpoint
- [x] Update group endpoint
- [x] Get group endpoint (includes list of roles in the group, this will not be stored on the group doc)
- [x] Get all groups endpoint 
- [ ] When a permissions reach is not specified, it defaults to the parent roles group 
- [x] When a roles group is not specified, it defaults to the "default" group
- [x] Update roles so that they are globally ranked
- [x] Link roles to groups
- [x] You cannot delete the default group
- [x] You cannot edit the default group

---------------------------------------
**PERMISSION AND REACH HANDLING**
- [x] Checks you have the permission required with an appropriate reach
- [x] Global reach overrides the need for group reach

---------------------------------------
**BALANCE PERMISSION HANDLING**
- [x] Creating/editing/deleting roles or groups can only be done by people with the built in admin role
- [x] Admin role cannot be edited or deleted
- [x] No roles can be ranked higher than the admin role 
- [ ] You cannot give someone a role that gives them access to permissions you don't have.
- [ ] You cannot give someone a role that gives them access to reach you don't have.

---------------------------------------
**INTERACTION PERMISSION HANDLING**
- [ ] You cannot give someone a role that is globally ranked higher or equal to your role.
- [ ] You cannot "interact" with another users data if that user has a higher or equal "global ranking" to you

---------------------------------------
**OPTIONAL??:** _(Curious as to if people feel these are needed if only Admin's are able to create roles)_
-  You cannot make a change that changes your overall reach w/o admin role.
-  You cannot make a change that changes your overall permissions w/o admin role.
-  You cannot make a change that changes your overall global ranking w/o admin role.
-  Admin role bypasses all permission checks (I have a feeling this should NOT be added because potentially we only want wellbeing officers to see wellbeing data)

**Comment by pumbas600** [comment]
This is going to be extremely overengineered but I love it haha.

In regards to the optional tasks, I feel like these two could be important:
- You cannot give someone a role that gives them access to permissions you don't have.
- You cannot give someone a role that gives them access to reach you don't have.

Especially as they'll likely want to give other users the `GIVE_ROLES` permission so that it's not all down to a single admin user. In this case, it's important to much sure they can't do these things.

The others as you mentioned don't feel particularly necessary. Worst case scenario we can always add them in later if needed :)

Goodluck!
