### ISSUE TITLE
Roles Page

### ISSUE THREAD

**Issue by long715** [UoaWDCC/AEYB#25]
### Outcome

As an admin, I am able to edit, add and delete user roles and permissions. 

### Moment

A functioning Roles Page will have: 
- roles sub-section view and buttons to add, delete, and select created roles 
- search bar to search for user profiles view
- permission sub-section view and buttons for
     -> general role permissions accessed via roles sub-section
     -> individual role permissions accessed via user profiles sub-section 

### Key Results

- [x] implement roles sub-section
- [x] implement search bar
- [x] Implement permissions
- [x] Code the desired design from the designer's wireframe
- [x] Code check by another developer
- [x] Create pull request

**Comment by luke-mccallum** [comment]
Solved in branch shown above
