### ISSUE TITLE
Setup and Create Database using MongoDB

### ISSUE THREAD

**Issue by hillaro** [UoaWDCC/AEYB#4]
### Outcome

As a Developer, I can view the database of all the board members' accounts

### Moment

Functioning database that we can populate with placeholder data

### Key Results

- [x] Create a Database using MongoDB
- [x] Connect to MongoDB Atlas
- [x] Discuss and Plan the relational database model

**Comment by pumbas600** [comment]
Hey Lauren, just in regards to this, did you create the MongoDB atlas db using a personal account or did you create a new account?

Also, do you reckon we should keep an up to date copy of the `config.json` file in the Google drive so that we can all easily get the configurations without making them publically available?

**Comment by lpar105** [comment]
Config in the google drive would definitely be useful. I think I should be able to invite everyone to the MongoDB Atlas project through their email of choice. But I've never tested that before so if it turns out to have limitations its easy enough to make a new account and update the config

**Comment by pumbas600** [comment]
That sounds great! :)

**Comment by hillaro** [comment]
> Config in the google drive would definitely be useful. I think I should be able to invite everyone to the MongoDB Atlas project through their email of choice. But I've never tested that before so if it turns out to have limitations its easy enough to make a new account and update the config

Here's a[ file in the Google Drive](https://docs.google.com/spreadsheets/d/11dg84kDNV_v00yfclaRBInp2IgQJ442syD6Q2ldm1a8/edit#gid=634347005) with everyone's preferred emails for this project!
And yep, feel free to add the `config.json` to the Google Drive!

**Comment by lpar105** [comment]
I've invited all backend developers to the mongoDB. @pumbas600 can you let me know if this is any good? Otherwise will switch to a shared account :)

**Comment by pumbas600** [comment]
Yeah, this should work, thanks!
