### ISSUE TITLE
Default permissions

### ISSUE THREAD

**Issue by jacobatan** [UoaWDCC/AEYB#99]
### Outcome

Currently, we don't have default permissions. This means that, when a user creates an account they cannot view any meetings or interact with the website. We want it such that they will have the default permission `VIEW_MEETINGS`.

1. Can either add the `VIEW_MEETINGS` permission to all users
2. OR, can remove the permission guard from the endpoint.
(The above will be up to the team to decide)

### Key Results

- [ ] When a user creates an account, make it so that they have the ability to view meetings.

**Comment by MrBatchiPapa** [comment]
Done :)
